# Mirror to GitHub

name: Mirror to GitHub

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  mirror:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - name: Configure Git
        run: |
          git config --global user.name "Mirror Bot"
          git config --global user.email "mirror@catboy.systems"
      
      - name: Push to GitHub
        run: |
          git remote add github https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/smol-kitten/MinecraftThroughTime.git || true
          git push github --all --force
          git push github --tags --force
        continue-on-error: true
